### ISSUE TITLE
Is it possible to move focus to an input automatically?

### ISSUE THREAD

**Issue by songcarver** [benjamindenboer/FramerInput#11]
This is a really beautiful module. Somehow I seem to be missing a method to move focus to a text field automatically. Another excellent module offers it:
https://github.com/ajimix/Input-Framer

**Comment by der-lukas** [comment]
input.focus() works!

**Comment by benjamindenboer** [comment]
Yes! You can also use the private `._inputElement` property to reference the element directly.
