### ISSUE TITLE
How can I disable the keyboard on the phone? I just want it to be like the demo on the mac.

### ISSUE THREAD

**Issue by Stanleylee01** [benjamindenboer/FramerInput#13]
Thanks for your great module!! 
I built a demo on the mac with your module while looks good. But when opened on the phone, the "original keyboard" on the phone shows with the fake simulate one. How can I disable the original one? 
Thanks a lot.

**Comment by benjamindenboer** [comment]
You can use` input._inputElement.blur()`. The blur element can be used on the actual Input Element.
