### ISSUE TITLE
Hide keyboard on mobile

### ISSUE THREAD

**Issue by tomasbana** [benjamindenboer/FramerInput#18]
It's possible hide the keyboard after entering the value and press Enter on your mobile phone?

**Comment by martinhalik** [comment]
plz

**Comment by martinhalik** [comment]
answer input._inputElement.blur()

**Comment by benjamindenboer** [comment]
Yes! The private `_inputElement` property refers to the actual HTML InputElement, and there you can use the `.blur()` method, within your `onTap` method.
