### ISSUE TITLE
[Bug] Input "text:" property issue when used inside flow component 

### ISSUE THREAD

**Issue by dannykeane** [benjamindenboer/FramerInput#3]
I've encountered an issue where the default "text:" property displays when used inside a flow component. This happens both when using the .wrap() function, and also when writing in plain code. As you can see from the screenshot, it's appearing using the default TextLayer properties. 

**Context:**
I use the input on a secondary screen within a flow component (not the primary screen). When the screen is active, the input appears like this.

**Code Used:**
`input = InputLayer.wrap(textarea, text, multiLine: true)`
_textarea is the name of my input background in design mode_ 

![ss](https://user-images.githubusercontent.com/425661/32709528-ece4d094-c7e5-11e7-99a3-4c4a9e226189.png)

**Comment by benjamindenboer** [comment]
Interesting. Thanks for reporting, I’ll dive in.

**Comment by benjamindenboer** [comment]
Got it! Thanks for reporting, @dannykeane.

**Comment by benjamindenboer** [comment]
Fixed with https://github.com/benjamindenboer/FramerInput/commit/eab1eb4f9fee9ed368c6fd1e1edee2635fd46b05.
