### ISSUE TITLE
Font size depends on device

### ISSUE THREAD

**Issue by akotomanov** [benjamindenboer/FramerInput#5]
If you change the device from iPhone 8 to something else, e.g. iPhone X, Nexus 5x, etc., you will get a tiny text in the input field.

<img width="366" alt="input_design_framer_and_input_design_framer" src="https://user-images.githubusercontent.com/326760/32810459-40e13c8a-c99b-11e7-9eb0-5ffb2833c1d1.png">

Text layers from Design tab have device-independent font size. But after wrapping to the component, they become dependent on screen density. 

<img width="690" alt="input_framer" src="https://user-images.githubusercontent.com/326760/32859242-2ca6ce3e-ca4e-11e7-9878-fa369f5aec03.png">

<img width="737" alt="input_framer_and_input_framer_and_documentation" src="https://user-images.githubusercontent.com/326760/32810715-8abbd166-c99c-11e7-99a5-2892a26f3c26.png">

**Comment by benjamindenboer** [comment]
Can no longer reproduce—closing instance.

**Comment by llewellynathan** [comment]
I'm still experiencing this issue.

**Comment by kyleartbow** [comment]
Yes, me too. My field is located in the Side menu bar. Here is a link: https://framer.cloud/pHTNb
